version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=gestionfoyer
      - MYSQL_ROOT_PASSWORD=root
    
  app:
    image: mondherar/springboot:latest
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

  frontend:
    image: mondherar/angular:latest
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - app
      - mysqldb
    
volumes:
  db:
