apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://mysql:3306/gestionfoyer
    spring.datasource.username=root
    spring.datasource.password=root
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    server.port=8080
